### ISSUE TITLE
Could not read from remote repository.

### ISSUE THREAD

**Issue by marcolombardini** [yasoob/nrc-exporter#7]
Another runner here looking to do the same. But I get the following: 

Warning: Permanently added 'github.com,140.82.112.3' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I'm using Linux/Chromebook

**Comment by yasoob** [comment]
Hi @marcolombardini  this has nothing to do with the repo. Your SSH settings are doing something funky. I have two quick and dirty solutions for you.

1. Clone using the https address rather than ssh. So you will basically run this command instead:
```
git clone https://github.com/yasoob/nrc-exporter.git
```

2. Download the project ZIP file instead. This can be done like this:
![image](https://user-images.githubusercontent.com/3696393/88222979-c98c4400-cc34-11ea-8531-ea3798061087.png)

I am closing this issue for now but if these steps don't resolve the problem, feel free to open it again.
